import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {" "}
        <div className="flex justify-center items-center p-16 pb-32 h-screen">
          <div className="flex justify-center items-center bg-white rounded-[20px] w-full h-full">
            {children}
            <Nav />
          </div>
        </div>
      </body>
    </html>
  );
}
